### ISSUE TITLE
Swimlane problem

### ISSUE THREAD

**Issue by EienFr** [vistree/kanboard-backlog#16]
Hi all,

It seems that I have a problem with this plugin. I don't have a unique column and swimlanes close to this. 

I have the column for each swimlane.

[Image](http://www.noelshack.com/2019-01-5-1546600287-backlog.png)

**Comment by creecros** [comment]
Please provide more info.

i.e.

Your configuration. And list of plug-ins being used.

**Comment by EienFr** [comment]
Sorry for forgot it.

Application version: 1.2.7
PHP version: 7.0.33
PHP SAPI: cgi-fcgi
OS version: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database driver: sqlite
Database version: 3.14.2 

Plugins 

Nebula | Valentino Pesce | 1.2.0
Calendar | Frédéric Guillot | 1.1.0
Backlog | vistree + creecros | 0.0.2
Bigboard | Thomas Stinner | 1.0.5
Customizer | Craig Crosby | 1.8.3
Coverimage | BlueTeck + creecros | 1.2.5.0

**Comment by EienFr** [comment]
Ok find the issue. Bigboard is the problem. Uninstall and now it's OK. Sorry for disturbing

**Comment by vistree** [comment]
Hi @EienFr : good you found it. Maybe we need to highlight the incompatibillity a bit more on the project description?!

**Comment by creecros** [comment]
Ya, probably wise, I doubt we could do anything to make it compatible with bigboard.

**Comment by creecros** [comment]
I think I can make them compatible. I'll work on it later tonight possibly.

**Comment by creecros** [comment]
tougher than I thought....maybe one day.

**Comment by vistree** [comment]
I'm quite sure we need to override the bigboard templates?!

**Comment by creecros** [comment]
ya, I tried that, it didn't seem to take. I think it would require cooperation with the bigboard repository
