### ISSUE TITLE
Column Collapsing

### ISSUE THREAD

**Issue by creecros** [vistree/kanboard-backlog#2]
Collapsing the columns itself work, but the width of the columns after collapsing should be minimised. Currently the width stays the same in the backlog-column regardless the column is collapsed or not and it seems that the width is not optimal lowered for the other columns (compared with the original board)

- [ ] make of _backlog-column to automatically resize in width after collapsing / uncollapsing AND append the free space to the other columns
- [ ] check if column size of other columns is optimised after collapsing them

**Comment by vistree** [comment]
@creecros : do you know if it is possible to extend a core kanboard js-function? Or if I can listen on those functions?
I need to add a class to my top level <td> if the inner column is collapsed.
Collapsing is done by 
`anboard.BoardColumnView.prototype.hideColumn = function (e) {
    $(".board-column-" + e + " .board-column-expanded").hide(), $(".board-column-" + e + " .board-column-collapsed").show(), $(".board-column-header-" + e + " .board-column-expanded").hide(), $(".board-column-header-" + e + " .board-column-collapsed").show(), $(".board-column-header-" + e).each(function () {
        $(this).removeClass("board-column-compact"), $(this).addClass("board-column-header-collapsed")
    }),
        $(".board-column-" + e).each(function () {
        $(this).addClass("board-column-task-collapsed")
    }), $(".board-column-" + e + " .board-rotation").each(function () {
        $(this).css("width", $(".board-column-" + e).height())
    }), localStorage.setItem("hidden_column_" + e, 1)
},`
in /kanboard-1.2.5/assets/js/app.min.js

**Comment by vistree** [comment]
I need to do my own stuff, when .hide() or .show() is called

**Comment by vistree** [comment]
No, I'm afraid that doesn't help. The problem is that the link to collapse the columns is in a popup that is loaded by Ajax. So the selector is not yet available when opening the board. So I thought I might react to a Kanboard event. But unfortunately I don't know how. 
What I need is to extend or react on Kanboard.BoardColumnView.prototype.hideColumn

**Comment by vistree** [comment]
Asked the question in kanboard forum: #https://github.com/kanboard/forum/issues/114

**Comment by creecros** [comment]
You can write your own js file, and attach the asset.

https://docs.kanboard.org/en/latest/plugins/hooks.html#asset-hooks

**Comment by vistree** [comment]
Yes, this is what I did ;-) Problem is, that I don't know how to react on the column collapsing / uncollapsing

**Comment by creecros** [comment]
I know very little about js unfortunately

**Comment by creecros** [comment]
you could override table_column.php and call your own class here:

https://github.com/kanboard/kanboard/blob/00228ac12fedaf436869289c7c114dc6f76dd14c/app/Template/board/table_column.php#L5

and add a condition like here:
https://github.com/vistree/kanboard-backlog/blob/37b08993a1a81d2caac5c9c511c9a9913fb2359e/Template/board/table_container.php#L31-L33

**Comment by creecros** [comment]
I'll take a look tonight. You probably know more than myself in regards to js though. I'll at least test the hell out of it and if I see no issues, merge and hope for the best.

**Comment by creecros** [comment]
it works, but not for the actual backlog column. when you expand, it freaks out:

![image](https://user-images.githubusercontent.com/26339368/47195478-1ccbb700-d32a-11e8-8d15-a83fbba11bdd.png)

a refresh fixes it.

easiest solution would be disable column collapsing in the backlog column when backlog mode is activated, at least until we can figure out the better solution.

**Comment by vistree** [comment]
It should work. Can you please clear browser cache and retry. If this does not help: which browser do you use?

**Comment by vistree** [comment]
Tested with firefox, Chrome and Safari on Mac OS X - all fine here

**Comment by creecros** [comment]
Cache cleared, same issue.
Chrome:
Version 69.0.3497.100 (Official Build) (64-bit)

Kanboard:
Application version: 1.2.6
PHP version: 7.2.10
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.45-rancher
Database driver: sqlite
Database version: 3.24.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by creecros** [comment]
if you want to test on my server:
https://projects.creecros.ml/

admin
admin

**Comment by vistree** [comment]
Thanx - using your server I repeated tests - and everything is fine. So maybe a browser related issue? Which OS + browser do you use?

**Comment by creecros** [comment]
Interesting.  

Using Latest windows and chrome.

**Comment by vistree** [comment]
Did you SHIFT + Reload (on Windows it mightbe also F5) to reload the whole page?

**Comment by creecros** [comment]
Yes. A reload does fixes it, but it still continues to do it. 

![image](https://github.com/creecros/empty/blob/master/backlog.gif?raw=true)

**Comment by vistree** [comment]
Will do some testing as soon I have a windows machine available

**Comment by creecros** [comment]
Does it in android too
![screenshot_2018-10-19-11-17-47](https://user-images.githubusercontent.com/26339368/47227423-ce053800-d390-11e8-90b0-dcad547204ef.png)

**Comment by vistree** [comment]
Ahh, I think the problem is, that the backlog-column has no min-width. Can you checkout the latest commit on column-branch?

**Comment by vistree** [comment]
OK, can you give it a try?

**Comment by creecros** [comment]
no change

**Comment by creecros** [comment]
Github was having issues last night. I couldn't get anything to work, I
started a merge but it just kept do in weird things. I was planning to
rename the backlog_board column, but only in display. It needs to remain a
unique name, to ensure no one has a column already named backlog.
