### ISSUE TITLE
Add ability to rename 'Backlog' column

### ISSUE THREAD

**Issue by AlgyTaylor** [vistree/kanboard-backlog#20]
Hi,

I like the backlog plugin, but want my column to be called "Requests" rather than "Backlog".  Would it be possible to add an option to change the name of that column, like I can on any other column on the board?

Thanks

**Comment by vistree** [comment]
H AlgyTaylor, 
this feature is not planned right now! Sorry.

**Comment by creecros** [comment]
Should be simple enough, I'll take care of it when I get a chance, just have a lot going on right now.

**Comment by creecros** [comment]
You'll find the option to set the Board title in Settings>Board Settings

**Comment by vistree** [comment]
Very cool - thanx creecros!!

**Comment by AlgyTaylor** [comment]
Thanks creecros - much appreciated, dude :+1:
