### ISSUE TITLE
Problems with PHP5

### ISSUE THREAD

**Issue by creecros** [vistree/kanboard-backlog#7]

**Comment by vistree** [comment]
Changed title, as PHP7.1 is already fixed by you (changing "===" to "==" in function moveTasksOut()

**Comment by vistree** [comment]
`` PHP Parse error:  syntax error, unexpected 'isset' (T_ISSET), expecting identifier (T_STRING) in /kanboard-1.2.5/plugins/Backlog/Model/ProjectUsesBacklogBoardModel.php on line 40
- [ ] replaced reserved string isset by backlogIsset

**Comment by vistree** [comment]
`PHP Parse error:  syntax error, unexpected 'unset' (T_UNSET), expecting identifier (T_STRING) in /kanboard-1.2.5/plugins/Backlog/Controller/BacklogBoardController.php on line 39`
- [ ]  replaced reserved string unset by backlogUnset

**Comment by vistree** [comment]
- [ ] change function set() to backlogSet() for reasons of consistency in 
`/kanboard-1.2.5/plugins/Backlog/Controller/BacklogBoardController.php on line 23`

**Comment by vistree** [comment]
Did some further testing. Everything works fine. Do you want to double check before I merge in master?

**Comment by creecros** [comment]
i'm good, merge away
